nome = input("Qual é o seu nome:")
sobrenome = input("Sobrenome: ")
idade = input("Sua idade:")
ano_nascimento = input("Ano de nascimento:")
maior_de_idade = idade >= 18
altura_metros = input("Altura em metros:")
print("»«"*6)
print("»«"*6)
print("Nome:",nome)
print("Sobrenome:",sobrenome)
print("Idade:",idade)
print("Ano de nascimento:",ano_nascimento)
print("É maior de idade:",maior_de_idade)
print("Altura em  metros:",altura_metros)