n = input("Digite um algo :")
print("O tipo primitivo desse valor é ", type(n))
print("Só tem espaço?", (n.isspace()))
print("É numérico?", (n.isnumeric()))
print("É alfabético", (n.isalpha()))
print("É decimal?", (n.isdecimal()))
print("Identificador", (n.isidentifier()))
print("Esta Em maiúscula.", (n.islower()))
print("É um título?", (n.istitle()))